local textures = {
    [1]="tint_square",
 
	[2]="SharedMediaOrbDebuffGlow",
	[3]="SharedMediaOrbLowhpGlow",
	[4]="SharedMediaOrbFill",
	[5]="SharedMediaOrbFill2",
	[6]="SharedMediaOrbFill3",
	[7]="SharedMediaOrbFill4",
	[8]="SharedMediaOrbGloss",
	[9]="SharedMediaTargetRing",
	[10]="SharedMediaClover1",
	[11]="SharedMediaClover2",
	[12]="SharedMediaClover3",
	[13]="SharedMediaClover4",
	[14]="SharedMediaClover5",
	[15]="SharedMediaAluminium",
	[16]="SharedMediaCharcoal",
	[17]="SharedMediaCilo",
	[18]="SharedMediaDabs",
	[19]="SharedMediaGloss",
	[20]="SharedMediaGraphite",
	[21]="SharedMediaMelli",
	[22]="SharedMediaMelliDark",
	[23]="SharedMediaMelliDarkRough",
	[24]="SharedMediaMinimalist",
	[25]="SharedMediaOtravi",
	[26]="SharedMediaOutline",
	[27]="SharedMediaRain",
	[28]="SharedMediaRunes",
	[29]="SharedMediaSmooth",
	[30]="SharedMediaSmoothv2",
	[31]="SharedMediaSteel",
	[32]="SharedMediaWater",
	[33]="SharedMediaHealbot",

	[34]="SharedMediaYCastbarBG",
	[35]="SharedMediaYGroupIconShape",
	[36]="SharedMediaYBar1",
	[37]="SharedMediaYCastbar1",
	[38]="SharedMediaYBar2",
	[39]="SharedMediaYCastbar2",
	[40]="SharedMediaYBar3",
	[41]="SharedMediaYCastbar3",
	[42]="SharedMediaYBar4",
	[43]="SharedMediaYCastbar4",
	[44]="SharedMediaYBar5",
	[45]="SharedMediaYCastbar5",
	
	[46]="xHUD_LeftRoundBarBG",
	[47]="xHUD_LeftRoundBarFG",
	[48]="xHUD_RightRoundBarBG",
	[49]="xHUD_RightRoundBarFG",
	[50]="xHUD_LeftGlowArcBG",
	[51]="xHUD_LeftGlowArcFG",
	[52]="xHUD_RightGlowArcBG",
	[53]="xHUD_RightGlowArcFG",
	[54]="xHUD_HorizontalFuzzyBarBG",
	[55]="xHUD_HorizontalFuzzyBarFG",
	[56]="xHUD_VerticalFuzzyBarBG",
	[57]="xHUD_VerticalFuzzyBarFG",
	[58]="xHUD_SancOrbBG",
	[59]="xHUD_SancOrbFG",
	[60]="xHUD_SancCenterFG",
	[61]="xHUD_SancCenterBG",
	[62]="xHUD_LeftMetalBG",
	[63]="xHUD_LeftMetalFG",
	[64]="xHUD_RightMetalBG",
	[65]="xHUD_RightMetalFG",
	[66]="xHUD_LeftPlainBG",
	[67]="xHUD_LeftPlainFG",
	[68]="xHUD_RightPlainBG",
	[69]="xHUD_RightPlainFG"
}

local displaynames = {
    [1]="Plain",
	[2]="SM-OrbDebuffGlow",
	[3]="SM-OrbLowhpGlow",
	[4]="SM-OrbFill",
	[5]="SM-OrbFill2",
	[6]="SM-OrbFill3",
	[7]="SM-OrbFill4",
	[8]="SM-OrbGloss",
	[9]="SM-TargetRing",
	[10]="SM-Clover1",
	[11]="SM-Clover2",
	[12]="SM-Clover3",
	[13]="SM-Clover4",
	[14]="SM-Clover5",
	
	[15]="SM-Aluminium",
	[16]="SM-Charcoal",
	[17]="SM-Cilo",
	[18]="SM-Dabs",
	[19]="SM-Gloss",
	[20]="SM-Graphite",
	[21]="SM-Melli",
	[22]="SM-MelliDark",
	[23]="SM-MelliDarkRough",
	[24]="SM-Minimalist",
	[25]="SM-Otravi",
	[26]="SM-Outline",
	[27]="SM-Rain",
	[28]="SM-Runes",
	[29]="SM-Smooth",
	[30]="SM-Smoothv2",
	[31]="SM-Steel",
	[32]="SM-Water",
	[33]="SM-Healbot",
	
    [34]="SM-YCastbarBG",
	[35]="SM-YGroupIconShape",
	[36]="SM-YBar1",
	[37]="SM-YCastbar1",
	[38]="SM-YBar2",
	[39]="SM-YCastbar2",
	[40]="SM-YBar3",
	[41]="SM-YCastbar3",
	[42]="SM-YBar4",
	[43]="SM-YCastbar4",
	[44]="SM-YBar5",
	[45]="SM-YCastbar5",

	[46]="xHUD_LeftRoundBarBG",
	[47]="xHUD_LeftRoundBarFG",
	[48]="xHUD_RightRoundBarBG",
	[49]="xHUD_RightRoundBarFG",
	[50]="xHUD_LeftGlowArcBG",
	[51]="xHUD_LeftGlowArcFG",
	[52]="xHUD_RightGlowArcBG",
	[53]="xHUD_RightGlowArcFG",
	[54]="xHUD_HorizontalFuzzyBarBG",
	[55]="xHUD_HorizontalFuzzyBarFG",
	[56]="xHUD_VerticalFuzzyBarBG",
	[57]="xHUD_VerticalFuzzyBarFG",
	[58]="xHUD_SancOrbBG",
	[59]="xHUD_SancOrbFG",
	[60]="xHUD_SancCenterFG",
	[61]="xHUD_SancCenterBG",
	[62]="xHUD_LeftMetalBG",
	[63]="xHUD_LeftMetalFG",
	[64]="xHUD_RightMetalBG",
	[65]="xHUD_RightMetalFG",
	[66]="xHUD_LeftPlainBG",
	[67]="xHUD_LeftPlainFG",
	[68]="xHUD_RightPlainBG",
	[69]="xHUD_RightPlainFG"	
}

local tiled = {
	["tint_square"] = true,
}

local dims = {
    ["tint_square"] = {32, 32},
	["SharedMediaOrbFill"] = { 256, 256 },
	["SharedMediaOrbFill2"] = { 256, 256 },
	["SharedMediaOrbFill3"] = { 256, 256 },
	["SharedMediaOrbFill4"] = { 256, 256 },
	["SharedMediaOrbLowhpGlow"] = { 256, 256 },
	["SharedMediaOrbDebuffGlow"] = { 256, 256 },
	["SharedMediaOrbGloss"] = { 256, 256 },
	["SharedMediaTargetRing"] = { 256, 256 },
	["SharedMediaClover1"] = { 256, 256 },
	["SharedMediaClover2"] = { 256, 256 },
	["SharedMediaClover3"] = { 256, 256 },
	["SharedMediaClover4"] = { 256, 256 },
	["SharedMediaClover5"] = { 256, 256 },	
	["SharedMediaAluminium"] = {256,32},
	["SharedMediaCharcoal"] = {256,32},
	["SharedMediaCilo"] = {256,32},
	["SharedMediaDabs"] = {256,32},
	["SharedMediaGloss"] = {256,32},
	["SharedMediaGraphite"] = {256,32},
	["SharedMediaHealbot"] = {256,32},
	["SharedMediaMelli"] = {256,32},
	["SharedMediaMelliDark"] = {256,32},
	["SharedMediaMelliDarkRough"] = {256,32},
	["SharedMediaMinimalist"] = {256,32},
	["SharedMediaOtravi"] = {256,32},
	["SharedMediaOutline"] = {256,32},
	["SharedMediaRain"] = {256,32},
	["SharedMediaRunes"] = {256,32},
	["SharedMediaSmooth"] = {256,32},
	["SharedMediaSmoothv2"] = {256,32},
	["SharedMediaSteel"] = {256,32},
	["SharedMediaWater"] = {256,32},
	
	["SharedMediaYCastbarBG"] = { 512, 128 },
	["SharedMediaYGroupIconShape"] = { 50, 50 },
	["SharedMediaYBar1"] = { 256, 64 },
	["SharedMediaYCastbar1"] = { 512, 128 },
	["SharedMediaYBar2"] = { 256, 64 },
	["SharedMediaYCastbar2"] = { 512, 128 },
	["SharedMediaYBar3"] = { 256, 64 },
	["SharedMediaYCastbar3"] = { 512, 128 },
	["SharedMediaYBar4"] = { 256, 64 },
	["SharedMediaYCastbar4"] = { 512, 128 },
	["SharedMediaYBar5"] = { 256, 64 },
	["SharedMediaYCastbar5"] = { 512, 128 },
	
	["xHUD_LeftRoundBarBG"] = {128,512},
	["xHUD_LeftRoundBarFG"] = {128,512},
	["xHUD_RightRoundBarBG"] = {128,512},
	["xHUD_RightRoundBarFG"] = {128,512},
	["xHUD_LeftGlowArcBG"] = {128,512},
	["xHUD_LeftGlowArcFG"] = {128,512},
	["xHUD_RightGlowArcBG"] = {128,512},
	["xHUD_RightGlowArcFG"] = {128,512},
	["xHUD_HorizontalFuzzyBarBG"] = {256,32},
	["xHUD_HorizontalFuzzyBarFG"] = {256,32},
	["xHUD_VerticalFuzzyBarBG"] = {32,256},
	["xHUD_VerticalFuzzyBarFG"] = {32,256},
	["xHUD_SancOrbBG"] = {256,256},
	["xHUD_SancOrbFG"] = {256,256},
	["xHUD_SancCenterFG"] = {256,256},
	["xHUD_SancCenterBG"] = {256,256},
	["xHUD_LeftMetalBG"] = {128,512},
	["xHUD_LeftMetalFG"] = {128,512},
	["xHUD_RightMetalBG"] = {128,512},
	["xHUD_RightMetalFG"] = {128,512},
	["xHUD_LeftPlainBG"] = {128,512},
	["xHUD_LeftPlainFG"] = {128,512},
	["xHUD_RightPlainBG"] = {128,512},
	["xHUD_RightPlainFG"] = {128,512},
}


	

	

local tags = {
    ["tint_square"] = {statusbar=true,background=true,verticalbar=true,border=true},
	["SharedMediaOrbFill"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaOrbFill2"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaOrbFill3"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaOrbFill4"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaOrbLowhpGlow"] = {statusbar=true},
	["SharedMediaOrbDebuffGlow"] = {statusbar=true},
	["SharedMediaOrbGloss"] = {statusbar=true},
	["SharedMediaTargetRing"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaClover1"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaClover2"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaClover3"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaClover4"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaClover5"] = {statusbar=true,background=true,verticalbar=true},
	
	["SharedMediaAluminium"] = {statusbar=true},
	["SharedMediaCilo"] = {statusbar=true},
	["SharedMediaDabs"] = {statusbar=true},
	["SharedMediaGloss"] = {statusbar=true},
	["SharedMediaGraphite"] = {statusbar=true},
	["SharedMediaGrid"] = {statusbar=true},
	["SharedMediaHealbot"] = {statusbar=true},
	["SharedMediaMelli"] = {statusbar=true},
	["SharedMediaMelliDark"] = {statusbar=true},
	["SharedMediaMelliDarkRough"] = {statusbar=true},
	["SharedMediaMinimalist"] = {statusbar=true},
	["SharedMediaOtravi"] = {statusbar=true},
	["SharedMediaOutline"] = {statusbar=true},
	["SharedMediaRain"] = {statusbar=true},
	["SharedMediaRunes"] = {statusbar=true},
	["SharedMediaSmooth"] = {statusbar=true},
	["SharedMediaSmoothv2"] = {statusbar=true},
	["SharedMediaSteel"] = {statusbar=true},
	["SharedMediaWater"] = {statusbar=true},
	
	["SharedMediaYCastbarBG"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaYGroupIconShape"] = {statusbar=true,background=true,verticalbar=true},
	["SharedMediaYBar1"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYCastbar1"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYBar2"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYCastbar2"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYBar3"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYCastbar3"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYBar4"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYCastbar4"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYBar5"] = {statusbar=true,background=false,verticalbar=true},
	["SharedMediaYCastbar5"] = {statusbar=true,background=false,verticalbar=true},
	
	["xHUD_LeftRoundBarBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_LeftRoundBarFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_RightRoundBarBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_RightRoundBarFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_LeftGlowArcBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_LeftGlowArcFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_RightGlowArcBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_RightGlowArcFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_HorizontalFuzzyBarBG"] = {statusbar=true,background=true,verticalbar=false},
	["xHUD_HorizontalFuzzyBarFG"] = {statusbar=true,background=false,verticalbar=false},
	["xHUD_VerticalFuzzyBarBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_VerticalFuzzyBarFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_SancOrbBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_SancOrbFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_SancCenterBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_SancCenterFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_LeftMetalBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_LeftMetalFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_RightMetalBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_RightMetalFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_LeftPlainBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_LeftPlainFG"] = {statusbar=true,background=false,verticalbar=true},
	["xHUD_RightPlainBG"] = {statusbar=true,background=true,verticalbar=true},
	["xHUD_RightPlainFG"] = {statusbar=true,background=false,verticalbar=true},
}

local LSA = LibStub("LibSharedAssets")
if not LSA then return end

for k,texName in ipairs(textures) do
	local metadata = {
			displayname = displaynames[k],
			size = dims[texName],
			tiled = tiled[texName] or false,
			tags = tags[texName],
		}
	local result = LSA:RegisterTexture(texName, metadata)
	if not result then
		LSA:AddMetadata(texName, {displayname = displaynames[k]})
	end
end